name: Release Indivdual Charts

on:
  push:
    branches:
      - main
    paths:
      - '!.github/**'
      - '!README.md'
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"

      - name: Commit files
        run: |
          git config --local user.email "robot@jade.team"
          git config --local user.name "GitHub Action"
          git commit -m "Added changes to non datarepo charts" -a
          git diff
          git push
