---
name: Helm Chart Lint
env:
  GOOGLE_APPLICATION_CREDENTIALS: /tmp/sa.json

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Import Vault secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.ROLE_ID }}
          secretId: ${{ secrets.SECRET_ID }}
          secrets: secret/devops/terraform/dev/cda/helm-gcr-service-account.json $base64decode(key) | APPLICATION_CREDENTIALS ;

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Test Kind Cluster
        run: kubectl cluster-info

      - name: Configure imagePullSecrets
        run: |
          kubectl create secret docker-registry gcr-json-key \
            --docker-server=gcr.io \
            --docker-username=_json_key \
            --docker-password="$(echo $APPLICATION_CREDENTIALS)" \
            --docker-email=any@valid.email
          kubectl patch serviceaccount default \
            -p '{"imagePullSecrets": [{"name": "gcr-json-key"}]}'
          kubectl get secret gcr-json-key -o yaml

#      - name: Run chart-testing (install)
#        run: ct install
